/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soesoemoo_pbo;

import static soesoemoo_pbo.endframe.kolomEnd;

/**
 *
 * @author Admin
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelJudul = new javax.swing.JLabel();
        LabelBiaya = new javax.swing.JLabel();
        LabelAlamat = new javax.swing.JLabel();
        LabelRasa = new javax.swing.JLabel();
        LabelKec = new javax.swing.JLabel();
        LabelOngkir = new javax.swing.JLabel();
        LabelSusu = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelSusu1 = new javax.swing.JLabel();
        pilihVarian = new javax.swing.JComboBox<>();
        pilihKecamatan = new javax.swing.JComboBox<>();
        kolomBiaya = new javax.swing.JTextField();
        kolomOngkir = new javax.swing.JTextField();
        kolomJumlah = new javax.swing.JTextField();
        kolomAlamat = new javax.swing.JTextField();
        kolomNama = new javax.swing.JTextField();
        kolomHarga = new javax.swing.JTextField();
        ButtonKirim = new javax.swing.JButton();
        ButtonCekHarga = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJudul.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        LabelJudul.setText("MENU ORDER");
        getContentPane().add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, -1));

        LabelBiaya.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelBiaya.setText("BIaya TOTAL");
        getContentPane().add(LabelBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        LabelAlamat.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelAlamat.setText("Alamat");
        getContentPane().add(LabelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        LabelRasa.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelRasa.setText("Varian Rasa");
        getContentPane().add(LabelRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        LabelKec.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelKec.setText("Kecamatan");
        getContentPane().add(LabelKec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        LabelOngkir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelOngkir.setText("Ongkir");
        getContentPane().add(LabelOngkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        LabelSusu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelSusu.setText("JUMLAH");
        getContentPane().add(LabelSusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        LabelNama.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelNama.setText("NAMA");
        getContentPane().add(LabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 20));

        LabelSusu1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        LabelSusu1.setText("SUSU");
        getContentPane().add(LabelSusu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        pilihVarian.setBackground(new java.awt.Color(204, 204, 204));
        pilihVarian.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pilihVarian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Original", "Chocolate", "Chocoberry", "Green Matcha" }));
        getContentPane().add(pilihVarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 190, 30));

        pilihKecamatan.setBackground(new java.awt.Color(204, 204, 204));
        pilihKecamatan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pilihKecamatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tembalang", "Banyumanik", "Candisari", "Gajahmungkur", "Gayamsari", "Genuk", "Gunungpati", "Mijen", "Ngaliyan", "Pedurungan", "Semarang Barat", "Semarang Selatan", "Semarang Tengah", "Semarang Timur", "Semarang Utara", "Tugu" }));
        getContentPane().add(pilihKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 190, 30));

        kolomBiaya.setBackground(new java.awt.Color(204, 204, 204));
        kolomBiaya.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kolomBiaya.setToolTipText("");
        kolomBiaya.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 190, 30));

        kolomOngkir.setBackground(new java.awt.Color(204, 204, 204));
        kolomOngkir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kolomOngkir.setToolTipText("");
        kolomOngkir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomOngkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 190, 30));

        kolomJumlah.setBackground(new java.awt.Color(204, 204, 204));
        kolomJumlah.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kolomJumlah.setToolTipText("");
        kolomJumlah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kolomJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolomJumlahKeyTyped(evt);
            }
        });
        getContentPane().add(kolomJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, 30));

        kolomAlamat.setBackground(new java.awt.Color(204, 204, 204));
        kolomAlamat.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kolomAlamat.setToolTipText("");
        kolomAlamat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, 30));

        kolomNama.setBackground(new java.awt.Color(204, 204, 204));
        kolomNama.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kolomNama.setToolTipText("");
        kolomNama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, 30));

        kolomHarga.setBackground(new java.awt.Color(204, 204, 204));
        kolomHarga.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kolomHarga.setToolTipText("");
        kolomHarga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 190, 30));

        ButtonKirim.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ButtonKirim.setText("Order");
        ButtonKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKirimActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 120, 40));

        ButtonCekHarga.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ButtonCekHarga.setText("Cek Harga");
        ButtonCekHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCekHargaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCekHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        Background.setFont(new java.awt.Font("Codian October Nine", 0, 13)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soesoemoo_pbo/GUI.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCekHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCekHargaActionPerformed
    int kecamatan = pilihKecamatan.getSelectedIndex();
    int rasa = pilihVarian.getSelectedIndex();
    int jumlah = Integer.valueOf(kolomJumlah.getText());
    int ongkir = 0;
    int susu = 0;
    int total = 0;
    switch(kecamatan){
        case (0):
            ongkir = 0;
            break;
        case (1):
            ongkir = 500;
            break;
        case (2):
            ongkir = 1000;
            break;
        case (3):
            ongkir = 1500;
            break;
        case (4):
            ongkir = 2000;
            break;
        case (5):
            ongkir = 2500;
            break;
        case (6):
            ongkir = 3000;
            break;
        case (7):
            ongkir = 3500;
            break;
        case (8):
            ongkir = 4000;
            break;
        case (9):
            ongkir = 4500;
            break;
        case (10):
            ongkir = 5000;
            break;
        case (11):
            ongkir = 5500;
            break;
        case (12):
            ongkir = 6000;
            break;
        case (13):
            ongkir = 6500;
            break;
        case (14):
            ongkir = 7000;
            break;
        case (15):
            ongkir = 7500;
            break;
        }
    switch(rasa){
        case (0):
            susu = 5000 * jumlah;
            break;
        case (1):
            susu = 7000 * jumlah;
            break;
        case (2):
            susu = 7000 * jumlah;
            break;
        case (3):
            susu = 7000 * jumlah;
            break;
       }
    total = ongkir + susu;
    kolomHarga.setText("Rp. " + susu );
    kolomOngkir.setText("Rp. " + ongkir );
    kolomBiaya.setText("Rp. " + total );
    }//GEN-LAST:event_ButtonCekHargaActionPerformed

    private void ButtonKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKirimActionPerformed
    int kecamatan = pilihKecamatan.getSelectedIndex();
    int rasa = pilihVarian.getSelectedIndex();    
        endframe fr3 = new endframe ();
        fr3.setVisible(true);
    kolomEnd.setText("Terima kasih "+kolomNama.getText()+" telah memesan susu sapi murni di SOESOEMOO, pesanan anda yaitu "+kolomJumlah.getText()
    +" buah Susu "+pilihVarian.getItemAt(rasa)+ " akan dikirimkan dalam beberapa menit ke "+kolomAlamat.getText()+" Kec. "+pilihKecamatan.getItemAt(kecamatan)
    +".\n\nSiapkan uang sebesar "+kolomBiaya.getText()+" untuk pembayaran Cash on Delivery (biaya sudah termasuk ongkir).\n\nSemoga hari anda menyenangkan karena sudah nyusu hari ini.");
    }//GEN-LAST:event_ButtonKirimActionPerformed

    private void kolomJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomJumlahKeyTyped
        char enter=evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_kolomJumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    public javax.swing.JButton ButtonCekHarga;
    public javax.swing.JButton ButtonKirim;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelBiaya;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelKec;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelOngkir;
    private javax.swing.JLabel LabelRasa;
    private javax.swing.JLabel LabelSusu;
    private javax.swing.JLabel LabelSusu1;
    public static javax.swing.JTextField kolomAlamat;
    public static javax.swing.JTextField kolomBiaya;
    public static javax.swing.JTextField kolomHarga;
    public static javax.swing.JTextField kolomJumlah;
    public static javax.swing.JTextField kolomNama;
    public static javax.swing.JTextField kolomOngkir;
    public static javax.swing.JComboBox<String> pilihKecamatan;
    public static javax.swing.JComboBox<String> pilihVarian;
    // End of variables declaration//GEN-END:variables
}
